# grafana docker-compose.yml
version: "3"
services:
  # grafana
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "9000:3000"
    volumes:
      - $HOME/data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
  # prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - $HOME/data/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    
